services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: infra-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    networks:
      - infra-net
  # portainer:
  #   image: portainer/portainer-ce:2.20.3
  #   container_name: infra-portainer
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./portainer_data:/data
  #   networks:
  #     - infra-net

networks:
  infra-net:
    external: true
