# ==========================================
# HTTP → REDIRECT + CERTBOT
# ==========================================
server {
    listen 80;
    listen [::]:80;

    # Aplica limite de requisições
    limit_req zone=one burst=20 nodelay;
    
    # Aplica limite de conexões simultâneas
    limit_conn addr 10;

    server_name felipeferraz.site www.felipeferraz.site;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# ==========================================
# HTTPS
# ==========================================
server {
    listen 443 ssl http2 reuseport;
    listen [::]:443 ssl http2 reuseport;

    # HTTP/3 QUIC
    listen 443 quic reuseport;
    listen [::]:443 quic reuseport;

    # HTTP/3 (QUIC)
    listen 443 quic reuseport;
    listen [::]:443 quic reuseport;

    server_name felipeferraz.site www.felipeferraz.site;

    ssl_certificate     /etc/letsencrypt/live/felipeferraz.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/felipeferraz.site/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    # HTTP/3 Alt-Svc
    add_header Alt-Svc 'h3=":443"'; 

    # ==========================================
    # SECURITY HEADERS
    # ==========================================
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Aplica limite de requisições
    limit_req zone=one burst=20 nodelay;
    
    # Aplica limite de conexões simultâneas
    limit_conn addr 10;

    # ==========================================
    # CERTBOT
    # ==========================================
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    # Cache de arquivos estáticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4|webp)$ {
        expires 30d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    # ==========================================
    # DEFAULT RESPONSE (infra test)
    # ==========================================
    location / {
        default_type text/plain;
        return 200 "felipeferraz.site - infra OK\n";
    }
}

#server {
#    listen 80;
#    server_name felipeferraz.site www.felipeferraz.site;
#
#    location /.well-known/acme-challenge/ {
#        root /var/www/certbot;
#    }
#
#    location / {
#        return 200 "felipeferraz.site - infra OK\n";
#    }
#}
